In [1]:
u = [2,2]
v = [1,2]
z = [-3,5]

In [13]:
result = []

In [14]:
for i in range(len(u)):
    result.append(u[i]+v[i]+z[i])    


In [15]:
print(result)

[0, 9]


In [8]:
result =[sum(t) for t in zip(u,v,z)]
print(result)

[0, 9]


In [1]:
import numpy as np

In [2]:
nu = np.array([2,2])
nv = np.array([1,2])
nz = np.array([-3,5])

In [3]:
sum = nu + nv + nz
print(sum)

[0 9]


In [4]:
u = [1,2,3]
v = [4,3,3]
alpha = 2

In [8]:
del sum

In [9]:
result = [alpha * sum(t) for t in zip(u,v)]
print(result)

[10, 10, 12]


In [13]:
nu = np.array([1,2,3])
nv = np.array([4,3,3])
alpha = 2
result = alpha*(nu+nv)
print(result)

[10 10 12]


In [23]:
matrix_a =[[3,6],[4,5]]
matrix_b = [[5,8],[6,7]]


In [25]:
result = [[sum(row) for row in zip(*t)] for t in zip(matrix_a, matrix_b)]
print(result)

[[8, 14], [10, 12]]


In [27]:
ma = np.array([[3,6],[4,5]])
mb = np.array([[5,8],[6,7]])

result = ma + mb
print(result)

[[ 8 14]
 [10 12]]


In [59]:
# a = [[1,2,3], [4,5,6]]
# a_t = [[1,4], [2,5], [3,6]] 

matrix_a = [[1,2,3],[4,5,6]]


#matrix_a_t = tuple(zip(matrix_a[0],matrix_a[1]))
#matrix_a_t = tuple(zip(matrix_a[i] for i in len(matrix_a)))
#print(matrix_a_t)

#matrix_a[i] for i in len(matrix_a)

In [61]:
result = [[element for element in t] for t in zip(*matrix_a)]
print(result)

[[1, 4], [2, 5], [3, 6]]


In [62]:
matrix_a = np.array([[1,2,3], [4,5,6]])
matrix_a_t = matrix_a.T
matrix_a_t2 = np.transpose(matrix_a)
print(matrix_a_t)
print(matrix_a_t2)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
